import { i18n, t } from "@/i18n";

const STATES = new Set([
  "blocked_by_unassigned_issue", "blocked_by_assigned_backlog_issue",
  "blocked_by_uninvokable_assignee", "blocked_by_cancelled_issue",
  "invalid_review_participant", "in_review_without_action_path",
]);

export function recoveryPreviewStateDisplay(state: string): string {
  if (!i18n.resolvedLanguage?.startsWith("ru") || !STATES.has(state)) return state.replace(/_/g, " ");
  return t(`localizationIssueLists.blocked_${state}`);
}

// These full-message patterns are generated by stable recovery/issue-graph-liveness.
// Unknown diagnostics stay verbatim; identifiers and the stored reason are never rewritten.
const REASONS: Array<{ pattern: RegExp; key: string; fields: string[] }> = [
  { pattern: /^(.+) is in review, but current participant agent is (.+)\.$/, key: "reviewAgentStatus", fields: ["issue", "status"] },
  { pattern: /^(.+) is in review, but current participant agent cannot be resolved\.$/, key: "reviewAgentMissing", fields: ["issue"] },
  { pattern: /^(.+) is in review, but its current participant cannot be resolved\.$/, key: "reviewParticipantMissing", fields: ["issue"] },
  { pattern: /^(.+) is in review with an agent assignee but no participant, interaction, approval, user owner, wake, active run, or recovery issue owning the next action\.$/, key: "reviewNoPath", fields: ["issue"] },
  { pattern: /^(.+) is still blocked by cancelled issue (.+)\.$/, key: "cancelledBlocker", fields: ["issue", "blocker"] },
  { pattern: /^(.+) is blocked by assigned backlog issue (.+) with no wake, active run, human owner, interaction, approval, monitor, or recovery issue owning the next action\.$/, key: "backlogBlocker", fields: ["issue", "blocker"] },
  { pattern: /^(.+) is blocked by unassigned issue (.+) with no user owner\.$/, key: "unassignedBlocker", fields: ["issue", "blocker"] },
  { pattern: /^(.+) is blocked by (.+), but its assignee no longer exists\.$/, key: "missingAssignee", fields: ["issue", "blocker"] },
  { pattern: /^(.+) is blocked by (.+), but its assignee is (.+)\.$/, key: "assigneeStatus", fields: ["issue", "blocker", "status"] },
];

export function recoveryPreviewReasonDisplay(reason: string): string {
  if (!i18n.resolvedLanguage?.startsWith("ru")) return reason;
  for (const rule of REASONS) {
    const match = rule.pattern.exec(reason);
    if (!match) continue;
    const values = Object.fromEntries(rule.fields.map((field, index) => [field, match[index + 1]]));
    if (values.status === "in an invalid org chain") values.status = t("stableRecovery.invalidOrgChain");
    else if (values.status) {
      const key = `status.${values.status}`;
      const label = t(key);
      if (label !== key) values.status = label;
    }
    return t(`stableRecovery.reason.${rule.key}`, values);
  }
  return reason;
}

export function recoveryPreviewErrorDisplay(error: string): string {
  const keys: Record<string, string> = {
    "Lookback hours must be a whole number from 1 to 720.": "invalidHours",
    "Failed to preview recovery tasks.": "previewFailed",
    "Failed to create recovery tasks.": "createFailed",
  };
  return keys[error] ? t(`stableRecovery.${keys[error]}`) : error;
}
